version: '3.4'

services:
  postgres:

    container_name: thread-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thread
      - POSTGRES_DB=thread
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
